export const data = [
  [
    { value: "3AJFJFJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "39HJJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "REJECTED", align: "left" },
  ],
  [
    { value: "3JDKD9", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "9HSHHS", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "DKD8DND", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "DJD8DN", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "9SSJSD", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "10JJDD", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "REJECTED", align: "left" },
  ],
  [
    { value: "2HDJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "5JDJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "8JDJJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "APPROVED", align: "left" },
  ],
  [
    { value: "IIS7SHJS", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "7HSJS1NN", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "109BDHJD", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
  [
    { value: "JDJD7HH", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
  ],
];

export const statusBtnColor = {
  PENDING: "info",
  APPROVED: "success",
  REJECTED: "error",
};

export const columns = [
  { name: "OrderId", align: "left" },
  { name: "Supplier", align: "left" },
  { name: "Shipping Date", align: "left" },
  { name: "Total Cost", align: "left" },
  { name: "Department", align: "left" },
  { name: "Status", align: "left", isButton: true },
];
