export const data = [
  [
    { value: "3AJFJFJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "39HJJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "REJECTED", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "3JDKD9", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "9HSHHS", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "DKD8DND", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "DJD8DN", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "9SSJSD", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "10JJDD", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "REJECTED", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "2HDJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "5JDJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "8JDJJDJ", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "APPROVED", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "IIS7SHJS", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "7HSJS1NN", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "109BDHJD", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
  [
    { value: "JDJD7HH", align: "left" },
    { value: "Lorem Ipsum", align: "left" },
    { value: "Thu, Feb 10", align: "left" },
    { value: "15, 000", align: "left" },
    { value: "300-123-938", align: "left" },
    { value: "PENDING", align: "left" },
    {
      orderProducts: [
        { id: "jhsjkkjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjjs882", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjs829", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjsj8", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkhj88hjj", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkkdkkd8899", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkjwii8820", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkk99www", qnty: 3, total: 300, status: "PENDING" },
        { id: "jhsjkkj0999uu", qnty: 3, total: 300, status: "PENDING" },
      ],
    },
  ],
];

export const statusBtnColor = {
  PENDING: "info",
  APPROVED: "success",
  REJECTED: "error",
};

export const columns = [
  { name: "OrderId", align: "left", value: "orderId" },
  { name: "Supplier", align: "left", value: "supplier" },
  { name: "Shipping Date", align: "left", value: "shippingDate" },
  { name: "Total Cost", align: "left", value: "totalCost" },
  { name: "Department", align: "left", value: "department" },
  { name: "Status", align: "left", isButton: true, value: "status" },
];

export const productsData = [
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjs882",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjjs882",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjs829",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhjkkjs008",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjsj8",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkk0900",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkhj88hjj",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkkdkkd8899",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjs882",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "098sjkkjs882",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjwii8820",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkk99www",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjsjsj99",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkj0999uu",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjuuu",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkk92mdmmd",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjjdnd",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkksms88",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkndmmd00",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkdmkdkjd",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjmddkk77",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjmnsdmnkj",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjssdjjkds0",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "jhsjkkjsjjsdkjsd",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
  {
    prodName: "Lorem Ipsum",
    id: "njsdjkjksd",
    price: "128",
    stock: 100,
    brand: "Brand Name",
    image:
      "https://static.vecteezy.com/system/resources/thumbnails/008/848/360/small/fresh-apple-fruit-free-png.png",
  },
];
